version: '3'
      
services:
      
  mysql:
      container_name: my_mysql
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: "12345"
      volumes:
          - ./.mysql:/var/lib/mysql   
