version: '3'
      
services:
      
  mysql:
      container_name: my_mysql
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: "12345"
      volumes:
          - ./.mysql:/var/lib/mysql
      
  wordpress:
      container_name: my_wordpress
      image: wordpress
      restart: always
      ports:
          - "8080:80"
      links:
          - mysql
      environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: "12345"
          WORDPRESS_DB_NAME: wordpress
      volumes:
          - ./wordpress:/var/www/html    
